### ISSUE TITLE
:rocket:  Portfolio: application deploy

### ISSUE THREAD

**Issue by mahabubx7** [mahabubx7/portfolio#10]
### :heavy_check_mark:  Deployed in GitHub-pages

Live link of the deployed site [click here](https://mahabubx7.github.io/portfolio/)

:medal_sports: Deployed :heavy_check_mark:

**Comment by gemmen29** [comment]
Hi @mahabubx7, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive issue ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mahabubx7** [comment]
Thanks @gemmen29 :+1:

**Comment by mahabubx7** [comment]
Approved and closed :heavy_check_mark:
